import { test, expect } from '@playwright/test';
test('Авторизация', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    await expect(page).toHaveURL('https://jpetstore.aspectran.com/account/signonForm')
    const locator = page.locator('[id="Signon"]')
    await expect(locator).toBeVisible()
    const panel = page.locator('[class="panel"]')
    await expect(panel).toBeVisible()
    const username = page.locator('[name="username"]')
    await expect(username).toBeVisible()
    await username.click()
    await username.type('redfoxa')
    const password = page.locator('[name="password"]')
    await expect(password).toBeVisible()
    await password.click()
    await password.type('redfoxa')
    const login = page.locator('[class="button-bar"]')
    await expect(login).toBeVisible()
    await login.click()
    const panelfailed = page.locator('[class="panel failed"]')
    await expect(panelfailed).toBeVisible()
    await expect(panelfailed).toContainText('Invalid username or password.  Signon failed.')
    const register = page.locator('[class="panel register"]')
    await expect(register).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('redfoxa')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('Mashinarium12')
    await login.click()
    await expect(panelfailed).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('redfoxa1')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('Mashinarium')
    await login.click()
    await expect(panelfailed).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('')
    await login.click()
    await expect(panelfailed).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('redfoxa')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('')
    await login.click()
    await expect(panelfailed).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('Mashinarium')
    await login.click()
    await expect(panelfailed).toBeVisible()
    await username.click()
    await username.press('Control+A')
    await username.press('Backspace')
    await username.type('redfoxa')
    await password.click()
    await password.press('Control+A')
    await password.press('Backspace')
    await password.type('Mashinarium')
    await login.click()
    const welcome = page.locator('[id="WelcomeContent"]')
    await expect(welcome).toBeVisible() 
})